### PR TITLE
adding global information

### PR DESCRIPTION
**Pull request by AndyHoggANU**
Have added what I think is appropriate data in the global part of this.
Includes splitting apart the `model.yaml` file to be model-specific.
I am yet to add a standard name for vicen.

### CODE REVIEW

**Comment by AndyHoggANU** [comment]
OK, now I've added an invented standard name for vicen.

**Comment by aidanheerdegen** [comment]
Actually `standard_name` is sacrosanct. Better not to have one if there is nothing listed in 

http://cfconventions.org/Data/cf-standard-names/69/build/cf-standard-name-table.html

**Comment by AndyHoggANU** [comment]
OK, but is there another field we can use to have a `non_standard_name` which explains what the variable is?

**Comment by aidanheerdegen** [comment]
`long_name`, or add a `comment` field for explanation. Comment can be a sentence.

**Comment by AndyHoggANU** [comment]
Better?

**Comment by aidanheerdegen** [comment]
I'll merge and make some changes.

**Pull request merged**
